### ISSUE TITLE
Customize nextJS repo

### ISSUE THREAD

**Issue by qafui** [Jim-Hodapp-Coaching/ambi-fe#1]
- [x] Update to typescript
- [x] Add a css framework/library
- [x] Configure testing with Jest
- [x] Setup linting
- [x] Updating readme with startup instructions
- [x] Add Open-Source license - BSD+ Patent

**Comment by naconnors** [comment]
Make sure to document in the README that this repo is starting at v0.5.0 to match the backend.

**Comment by naconnors** [comment]
Another possible option would be to use MaterialUI (https://mui.com/material-ui/).
