### ISSUE TITLE
Research real-time sensor-values display and updating

### ISSUE THREAD

**Issue by qafui** [Jim-Hodapp-Coaching/ambi-fe#2]
### Description
- Server-sent events via web socket?
- How does the above factor into client-side rendering?

### Output and Outcomes
- Present options and choose either
- [x] server-sent events
- [ ] client-side polling

> Document findings in a new discussion thread

**Comment by naconnors** [comment]
We should stick with SSE instead of moving to web sockets. Our use case is met by using SSE. I have a prototype that I can demo on Thursday to show how we can consume server sent events in the react fe.

**Comment by naconnors** [comment]
I don't think it is worth the time to explore client side polling for this task. From my experience it doesn't work as well push updates from the server. I will present my work at the next meeting and then if we decide it is still worth prototyping client side polling I can work on it. If we decide the SSE are a good option I will close this task and do the implementation work on #8

**Comment by jhodapp** [comment]
I agree @naconnors, is there really any possibility that we'd want to poll from the client side? I'm generally not a fan of polling for most things unless it's something that happens so infrequently that it's negligible resource-wise.

**Comment by naconnors** [comment]
Deciding to go with SSE. Closing.
